apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: name
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - name: volume
          mountPath: /pvc/
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: myvol
