apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: agarwalconsulting/versioned-nginx:liveness
    resources:
      requests:
        cpu: 100m
        memory: 20Mi
      limits:
        cpu: 500m
        memory: 100Mi
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
      failureThreshold: 2

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
  type: NodePort
