apiVersion: v1
kind: Pod
metadata:
  name: fib
spec:
  containers:
  - image: agarwalconsulting/fib-gen:alpine
    name: generator
    command: ["sh", "-c", "/app/fib >> /var/log/activity.log"]
    volumeMounts:
      - name: shared-logs
        mountPath: /var/log
    resources:
      requests:
        cpu: 100m
        memory: 20Mi
      limits:
        cpu: 500m
        memory: 100Mi
  volumes:
    - name: shared-logs
      emptyDir: {}
    #   # This GCE PD must already exist.
      # gcePersistentDisk:
      #   pdName: my-data-disk
      #   fsType: ext4
