apiVersion: v1
kind: LimitRange
metadata:
  name: mylimitrange
spec:
  limits:
    - default:
      cpu: 500m
      memory: 256Mi
    - defaultRequest
      cpu: 250m
      memory: 256Mi
    - min:
      cpu: 256m
      memory: 128Mi
    - max:
      cpu: 1000m
      memory: 1Gi
    type: Container
