apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 256Mi
      cpu: 200m
    max:
      memory: 1000Mi
      cpu: 1000m
    min:
      memory: 10Mi
      cpu: 100m
    type: Container
