# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: efk-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     # cert-manager.io/cluster-issuer: "letsencrypt-prod"
#     # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
# spec:
#   # tls:
#   #   - hosts:
#   #       # See devops/env/config.json & ./devops/scripts/k8s/update-urls.sh
#   #       - kibana.local
#   #     secretName: efk-tls

#   rules:
#     - host: kibana.local
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: logging-kb-http
#               servicePort: 5601
