apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: greeting-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: agarwalconsulting/spring-greeting
