---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: gs-rest
 spec:
   replicas: 2
   template:
     spec:
       containers:
         - name: spring-greeting
           image: gauravagarwalr/spring-greeting:latest
           ports:
             - containerPort: 8080
