apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs-rest
  labels:
    app: gs-rest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gs-rest
  template:
    metadata:
      labels:
        app: gs-rest
    spec:
      containers:
      - name: spring-greeting
        image: agarwalconsulting/spring-greeting:latest
        ports:
          - name: gs-port
            containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
